version: '3'
services:
  node-service:
    restart: unless-stopped
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
        - .:/app
    ports:
        - 3000:3000
        - 9229:9229