version: '3'
services:
  ci-node-server:
    restart: always
    env_file: ./server/.env
    build:
      context: ./server
    ports:
      - 5000:5000
  ci-client:
    stdin_open: true
    tty: true
    restart: always
    build:
      context: ./client
      args:
        - PUSH_SERVER_URL=host.docker.internal
        - PUSH_SERVER_PORT=9999
    environment:
      - NODE_ENV=production
    env_file: ./client/.env
  nginx:
    restart: always
    build:
      context: ./nginx
    depends_on:
      - ci-client
      - ci-node-server
    ports:
      - '3000:80'
  push-server:
    restart: always
    build:
      context: ./pushServer
    ports:
      - '9999:9999'